const presets={esaka:{name:"大阪・江坂",lat:34.7565,lon:135.4968},kyoto:{name:"京都市",lat:35.038,lon:135.774},kobe:{name:"神戸市",lat:34.6913,lon:135.1830},omiya:{name:"さいたま市大宮区",lat:35.906,lon:139.624},fukushima:{name:"福島市",lat:37.7608,lon:140.4747}};
const categories={indoor:['amenity=library','amenity=arts_centre','amenity=planetarium','amenity=theatre','amenity=cinema','tourism=museum','tourism=aquarium','shop=mall'],shade:['leisure=park','leisure=garden','tourism=attraction','landuse=forest'],water:['natural=water','water=lake','water=pond','leisure=marina','waterway=riverbank','beach=yes'],seating:['amenity=bench','leisure=park','tourism=attraction'],lowodor:['amenity=library','tourism=museum','amenity=planetarium','amenity=arts_centre']};
function speedToKmh(p){if(p==='slow')return 25;if(p==='fast')return 50;return 35;}
function haversine(a,b,c,d){const r=x=>x*Math.PI/180,R=6371,dLat=r(c-a),dLon=r(d-b);const A=Math.sin(dLat/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(A),Math.sqrt(1-A));}
function buildOverpassQuery(lat,lon,r){const tagSet=new Set(Object.values(categories).flat());const parts=[];tagSet.forEach(kv=>{const[k,v]=kv.split('=');parts.push(`node(around:${r*1000},${lat},${lon})[${k}=${v}];`);parts.push(`way(around:${r*1000},${lat},${lon})[${k}=${v}];`);parts.push(`relation(around:${r*1000},${lat},${lon})[${k}=${v}];`);});return `[out:json][timeout:25];\n(\n${parts.join('\n')}\n);\nout center 200;`;}
function mapProps(tags){const p={indoor:false,shade:false,water:false,seating:false,lowodor:false};const has=(k,v)=>tags[k]===v;if(has('amenity','library')||has('tourism','museum')||has('amenity','planetarium')||has('amenity','arts_centre')||has('tourism','aquarium')||has('shop','mall'))p.indoor=true;if(has('leisure','park')||has('leisure','garden')||has('landuse','forest'))p.shade=true;if(has('natural','water')||has('waterway','riverbank')||has('beach','yes'))p.water=true;if(has('amenity','bench')||has('leisure','park'))p.seating=true;if(has('amenity','library')||has('tourism','museum')||has('amenity','planetarium')||has('amenity','arts_centre'))p.lowodor=true;return p;}
function scoreSpot(spot,prio,lat,lon){const props=mapProps(spot.tags||{});const distKm=haversine(lat,lon,spot.lat,spot.lon);let s=0;for(const k of ['indoor','shade','water','seating','lowodor']){const p=prio[k];s+=(props[k]?p:p+2);}s+=distKm*0.3;return {score:s,props,distKm};}
function friendlyType(tags){if(tags.amenity==='library')return'図書館';if(tags.tourism==='museum')return'美術館/博物館';if(tags.tourism==='aquarium')return'水族館';if(tags.shop==='mall')return'ショッピングモール';if(tags.leisure==='park')return'公園';if(tags.leisure==='garden')return'庭園';if(tags.landuse==='forest')return'緑地';if(tags.amenity==='planetarium')return'プラネタリウム';if(tags.amenity==='theatre')return'劇場';if(tags.amenity==='cinema')return'映画館';return tags.tourism||tags.leisure||tags.amenity||'スポット';}
function shortDesc(s){const t=s.tags||{};const type=friendlyType(t);const dist=`約${(s.distKm).toFixed(1)}km`;const feats=[];if(s.props.indoor)feats.push('屋内');if(s.props.shade)feats.push('木陰');if(s.props.water)feats.push('水辺');if(s.props.seating)feats.push('ベンチ');if(s.props.lowodor)feats.push('匂い少');const featLine=feats.length?`（${feats.join('・')}）`:"";const base=t.description||t['short_description']||t.operator||'';return `${type}・${dist}${featLine}${base?`。${base}`:""}`;}
function gmapsLink(s){const lat=s.lat,lon=s.lon;return `https://www.google.com/maps/search/?api=1&query=${lat}%2C${lon}`;}
function appleMapsLink(s){const lat=s.lat,lon=s.lon;const q=encodeURIComponent(s.tags.name||s.tags['name:ja']||'目的地');return `https://maps.apple.com/?ll=${lat},${lon}&q=${q}`;}
function loadState(){try{return JSON.parse(localStorage.getItem("spotFilters")||"{}");}catch(_){return{};}}
function saveState(st){localStorage.setItem("spotFilters",JSON.stringify(st));}
function loadFavs(){try{return JSON.parse(localStorage.getItem("favorites")||"[]");}catch(_){return[];}}
function saveFavs(v){localStorage.setItem("favorites",JSON.stringify(v));}
function toggleFav(item){const favs=loadFavs();const idx=favs.findIndex(f=>String(f.id)===String(item.id));if(idx>=0){favs.splice(idx,1);}else{favs.push({id:item.id,name:item.name,lat:item.lat,lon:item.lon,tags:item.tags});}saveFavs(favs);}
async function searchOverpass(lat,lon,minutes,profile,prio,limit=10){const kmh=speedToKmh(profile);const r=Math.max(1,(kmh*(minutes/60))*0.6);const q=buildOverpassQuery(lat,lon,r);const url="https://overpass-api.de/api/interpreter";const res=await fetch(url,{method:"POST",body:q,headers:{"Content-Type":"text/plain"}});const json=await res.json();const elements=json.elements||[];const spots=elements.map(e=>{const latc=e.lat||(e.center&&e.center.lat);const lonc=e.lon||(e.center&&e.center.lon);const tags=e.tags||{};const name=tags.name||tags["name:ja"]||tags.amenity||tags.leisure||tags.tourism||"スポット";return {id:e.id,lat:latc,lon:lonc,tags,name};}).filter(s=>s.lat&&s.lon);const scored=spots.map(s=>{const r=scoreSpot(s,prio,lat,lon);return {...s,...r};}).sort((a,b)=>a.score-b.score);return scored.slice(0,limit);}
function renderSpotsList(items){const list=document.getElementById("spots");list.innerHTML="";if(!items.length){const li=document.createElement("li");li.className="spot";li.textContent="見つかりませんでした。条件を緩めて再検索してください。";list.appendChild(li);return;}
  items.forEach(s=>{const li=document.createElement("li");li.className="spot";const tags=[];if(s.props.indoor)tags.push("屋内");if(s.props.shade)tags.push("木陰");if(s.props.water)tags.push("水辺");if(s.props.seating)tags.push("ベンチ");if(s.props.lowodor)tags.push("匂い少");li.innerHTML=`<div><strong>${s.name}</strong><div class="meta">${shortDesc(s)}</div><div class="tags">${tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div></div><div class="actions"><a class="btn" target="_blank" rel="noopener" href="${gmapsLink(s)}">Googleマップ</a><a class="btn" target="_blank" rel="noopener" href="${appleMapsLink(s)}">Appleマップ</a><button class="btn star" data-id="${s.id}" title="お気に入りに追加/解除">⭐</button></div>`;list.appendChild(li);});
  list.querySelectorAll(".star").forEach(btn=>{btn.addEventListener("click",()=>{const id=btn.getAttribute("data-id");const item=items.find(i=>String(i.id)===String(id));if(!item)return;toggleFav(item);btn.classList.toggle("active");});});
}
async function runSearch(){const st=loadState();const region=document.getElementById("region");const driveMin=document.getElementById("driveMin");const speedProfile=document.getElementById("speedProfile");const prIndoor=document.getElementById("prio-indoor");const prShade=document.getElementById("prio-shade");const prWater=document.getElementById("prio-water");const prSeat=document.getElementById("prio-seating");const prOdor=document.getElementById("prio-lowodor");if(Object.keys(st).length){region.value=st.region||region.value;driveMin.value=st.driveMin||driveMin.value;speedProfile.value=st.speedProfile||speedProfile.value;prIndoor.value=st.indoor||prIndoor.value;prShade.value=st.shade||prShade.value;prWater.value=st.water||prWater.value;prSeat.value=st.seating||prSeat.value;prOdor.value=st.lowodor||prOdor.value;}let key=region.value;let lat,lon;if(key==="current"){try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:8000}));lat=pos.coords.latitude;lon=pos.coords.longitude;}catch(e){alert("現在地が取得できませんでした。江坂を使用します。");key="esaka";region.value="esaka";lat=presets.esaka.lat;lon=presets.esaka.lon;}}else{lat=presets[key].lat;lon=presets[key].lon;}const prio={indoor:parseInt(prIndoor.value,10)||1,shade:parseInt(prShade.value,10)||2,water:parseInt(prWater.value,10)||3,seating:parseInt(prSeat.value,10)||2,lowodor:parseInt(prOdor.value,10)||1};const minutes=parseInt(driveMin.value,10)||20;const profile=speedProfile.value;saveState({region:key,driveMin:minutes,speedProfile:profile,indoor:prio.indoor,shade:prio.shade,water:prio.water,seating:prio.seating,lowodor:prio.lowodor});try{const results=await searchOverpass(lat,lon,minutes,profile,prio,10);renderSpotsList(results);}catch(e){document.getElementById("spots").innerHTML="<li class='spot'>Overpassの取得に失敗しました。時間をおいて再試行してください。</li>";}}
function resetFilters(){localStorage.removeItem("spotFilters");document.getElementById("driveMin").value=20;document.getElementById("speedProfile").value="normal";document.getElementById("prio-indoor").value=1;document.getElementById("prio-shade").value=2;document.getElementById("prio-water").value=3;document.getElementById("prio-seating").value=2;document.getElementById("prio-lowodor").value=1;}
window.addEventListener("load",()=>{runSearch();if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js");}});
document.getElementById("addToHome").addEventListener("click",()=>alert("共有 → 『ホーム画面に追加』でアプリ化できます。"));
document.getElementById("searchSpots").addEventListener("click",runSearch);
document.getElementById("resetFilters").addEventListener("click",()=>{resetFilters();runSearch();});
