
(function(){
  const presets={esaka:{name:"大阪・江坂",lat:34.7565,lon:135.4968},kyoto:{name:"京都市",lat:35.038,lon:135.774},kobe:{name:"神戸市",lat:34.6913,lon:135.1830},omiya:{name:"さいたま市大宮区",lat:35.906,lon:139.624},fukushima:{name:"福島市",lat:37.7608,lon:140.4747}};
  function speedToKmh(p){if(p==='slow')return 25;if(p==='fast')return 50;return 35;}
  function rad(x){return x*Math.PI/180} const R=6371;
  function haversine(a,b,c,d){const dLat=rad(c-a),dLon=rad(d-b);const A=Math.sin(dLat/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(A),Math.sqrt(1-A));}
  const categories={indoor:['amenity=library','tourism=museum','amenity=planetarium','amenity=arts_centre','tourism=aquarium','shop=mall'],shade:['leisure=park','leisure=garden','landuse=forest'],water:['natural=water','water=lake','leisure=marina','waterway=riverbank'],seating:['amenity=bench','leisure=park'],lowodor:['amenity=library','tourism=museum','amenity=planetarium','amenity=arts_centre']};
  function buildOverpassQuery(lat,lon,r){const tagSet=new Set(Object.values(categories).flat());const parts=[];tagSet.forEach(kv=>{const[k,v]=kv.split('=');parts.push(`node(around:${r*1000},${lat},${lon})[${k}=${v}];`);parts.push(`way(around:${r*1000},${lat},${lon})[${k}=${v}];`);parts.push(`relation(around:${r*1000},${lat},${lon})[${k}=${v}];`);});return `[out:json][timeout:25];\n(\n${parts.join('\n')}\n);\nout center 200;`;}
  function mapProps(tags){const p={indoor:false,shade:false,water:false,seating:false,lowodor:false};const has=(k,v)=>tags&&tags[k]===v;if(has('amenity','library')||has('tourism','museum')||has('amenity','planetarium')||has('amenity','arts_centre')||has('tourism','aquarium')||has('shop','mall'))p.indoor=true;if(has('leisure','park')||has('leisure','garden')||has('landuse','forest'))p.shade=true;if(has('natural','water')||has('waterway','riverbank'))p.water=true;if(has('amenity','bench')||has('leisure','park'))p.seating=true;if(has('amenity','library')||has('tourism','museum')||has('amenity','planetarium')||has('amenity','arts_centre'))p.lowodor=true;return p;}
  function friendlyType(tags){if(!tags)return'スポット';if(tags.amenity==='library')return'図書館';if(tags.tourism==='museum')return'美術館/博物館';if(tags.tourism==='aquarium')return'水族館';if(tags.shop==='mall')return'ショッピングモール';if(tags.leisure==='park')return'公園';if(tags.leisure==='garden')return'庭園';if(tags.landuse==='forest')return'緑地';if(tags.amenity==='planetarium')return'プラネタリウム';return tags.tourism||tags.leisure||tags.amenity||'スポット';}
  function shortDesc(s){const t=s.tags||{};const type=friendlyType(t);const dist=`約${(s.distKm).toFixed(1)}km`;const feats=[];if(s.props.indoor)feats.push('屋内');if(s.props.shade)feats.push('木陰');if(s.props.water)feats.push('水辺');if(s.props.seating)feats.push('ベンチ');if(s.props.lowodor)feats.push('匂い少');const featLine=feats.length?`（${feats.join('・')}）`:"";return `${type}・${dist}${featLine}`;}
  function appleMapsLink(s){const q=encodeURIComponent((s.tags&&(s.tags.name||s.tags['name:ja']))||'目的地');return `https://maps.apple.com/?ll=${s.lat},${s.lon}&q=${q}`;}
  async function search(lat,lon,minutes,profile,limit=10){const kmh=speedToKmh(profile);const r=Math.max(1,(kmh*(minutes/60))*0.6);const q=buildOverpassQuery(lat,lon,r);const res=await fetch("https://overpass-api.de/api/interpreter",{method:"POST",body:q,headers:{"Content-Type":"text/plain"}});const json=await res.json();const es=(json.elements||[]).map(e=>{const latc=e.lat||(e.center&&e.center.lat);const lonc=e.lon||(e.center&&e.center.lon);const tags=e.tags||{};const name=tags.name||tags['name:ja']||tags['name:en']||'スポット';return {id:e.id,lat:latc,lon:lonc,tags,name};}).filter(x=>x.lat&&x.lon);
    const items=es.map(s=>{const props=mapProps(s.tags);const distKm=haversine(lat,lon,s.lat,s.lon);return {...s,props,distKm};}).sort((a,b)=>a.distKm-b.distKm).slice(0,limit);return items;}
  function render(items){const ul=document.getElementById('spots');ul.innerHTML='';if(!items.length){const li=document.createElement('li');li.className='spot';li.textContent='見つかりませんでした。';ul.appendChild(li);return;}items.forEach(s=>{const li=document.createElement('li');li.className='spot';li.setAttribute('data-lat',s.lat);li.setAttribute('data-lon',s.lon);li.setAttribute('data-name',s.name);li.innerHTML=`<div><strong>${s.name}</strong><div class='meta'>${shortDesc(s)}</div></div><div class='actions vstack'><button class='iconbtn gmaps' title='Googleマップで開く'><svg viewBox='0 0 24 24' aria-hidden='true'><path d='M12 2C7.6 2 4 5.6 4 10c0 6 8 12 8 12s8-6 8-12c0-4.4-3.6-8-8-8z' fill='#EA4335'/><circle cx='12' cy='10' r='5' fill='#fff'/><text x='12' y='13' text-anchor='middle' font-size='8' font-family='Arial' fill='#1a73e8' font-weight='700'>G</text></svg></button><a class='iconbtn amaps' target='_blank' rel='noopener' title='Appleマップで開く' href='${appleMapsLink(s)}'><svg viewBox='0 0 24 24' aria-hidden='true'><rect x='3' y='3' width='18' height='18' rx='4' fill='#e2e8f0' stroke='#cbd5e1'/><path d='M7 14l3-3 2 2 4-4' fill='none' stroke='#0ea5e9' stroke-width='2'/><circle cx='16' cy='9' r='2' fill='#94a3b8'/></svg></a></div>`;ul.appendChild(li);});}
  async function run(){let lat=34.7565,lon=135.4968;try{const items=await search(lat,lon,20,'normal',10);render(items);}catch(e){const ul=document.getElementById('spots');ul.innerHTML="<li class='spot'>取得に失敗しました。</li>";console.error(e);}}
  window.addEventListener('load',run);
})();
