const presets={esaka:{name:"大阪・江坂",lat:34.7565,lon:135.4968},kyoto:{name:"京都市",lat:35.038,lon:135.774},kobe:{name:"神戸市",lat:34.6913,lon:135.1830},omiya:{name:"さいたま市大宮区",lat:35.906,lon:139.624},fukushima:{name:"福島市",lat:37.7608,lon:140.4747}};
const categories={indoor:['amenity=library','amenity=arts_centre','amenity=planetarium','amenity=theatre','amenity=cinema','tourism=museum','tourism=aquarium','shop=mall'],shade:['leisure=park','leisure=garden','tourism=attraction','landuse=forest'],water:['natural=water','water=lake','water=pond','leisure=marina','waterway=riverbank','beach=yes'],seating:['amenity=bench','leisure=park','tourism=attraction'],lowodor:['amenity=library','tourism=museum','amenity=planetarium','amenity=arts_centre']};
function speedToKmh(p){if(p==='slow')return 25;if(p==='fast')return 50;return 35;}
function haversine(a,b,c,d){const r=x=>x*Math.PI/180,R=6371,dLat=r(c-a),dLon=r(d-b);const A=Math.sin(dLat/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(A),Math.sqrt(1-A));}
function buildOverpassQuery(lat,lon,r){const tagSet=new Set(Object.values(categories).flat());const parts=[];tagSet.forEach(kv=>{const[k,v]=kv.split('=');parts.push(`node(around:${r*1000},${lat},${lon})[${k}=${v}];`);parts.push(`way(around:${r*1000},${lat},${lon})[${k}=${v}];`);parts.push(`relation(around:${r*1000},${lat},${lon})[${k}=${v}];`);});return `[out:json][timeout:25];\n(\n${parts.join('\n')}\n);\nout center 200;`;}
function scoreSpot(spot,prio,lat,lon){const props={indoor:false,shade:false,water:false,seating:false,lowodor:false};const tags=spot.tags||{};const has=(k,v)=>tags[k]===v;if(has('amenity','library')||has('tourism','museum')||has('amenity','planetarium')||has('amenity','arts_centre')||has('tourism','aquarium')||has('shop','mall'))props.indoor=true;if(has('leisure','park')||has('leisure','garden')||has('landuse','forest'))props.shade=true;if(has('natural','water')||has('waterway','riverbank')||has('beach','yes'))props.water=true;if(has('amenity','bench')||has('leisure','park'))props.seating=true;if(has('amenity','library')||has('tourism','museum')||has('amenity','planetarium')||has('amenity','arts_centre'))props.lowodor=true;const distKm=haversine(lat,lon,spot.lat,spot.lon);let s=0;for(const k of ['indoor','shade','water','seating','lowodor']){const p=prio[k];s+=props[k]?p:p+2;}s+=distKm*0.3;return{score:s,props};}
async function searchOverpass(lat,lon,minutes,profile,prio,limit=10){const kmh=speedToKmh(profile);const r=Math.max(1,(kmh*(minutes/60))*0.6);const q=buildOverpassQuery(lat,lon,r);const url="https://overpass-api.de/api/interpreter";const res=await fetch(url,{method:"POST",body:q,headers:{"Content-Type":"text/plain"}});const json=await res.json();const elements=json.elements||[];const spots=elements.map(e=>{const latc=e.lat||(e.center&&e.center.lat);const lonc=e.lon||(e.center&&e.center.lon);return{id:e.id,lat:latc,lon:lonc,tags:e.tags||{}}}).filter(s=>s.lat&&s.lon);const scored=spots.map(s=>{const{score,props}=scoreSpot(s,prio,lat,lon);return{...s,score,props}}).sort((a,b)=>a.score-b.score);return scored.slice(0,10);}
function renderSpotsList(items){const list=document.getElementById("spots");list.innerHTML="";if(!items.length){const li=document.createElement("li");li.className="spot";li.textContent="見つかりませんでした。条件を緩めて再検索してください。";list.appendChild(li);return;}items.forEach(s=>{const name=s.tags.name||s.tags["name:ja"]||s.tags.amenity||s.tags.leisure||s.tags.tourism||"スポット";const tags=[];if(s.props.indoor)tags.push("屋内");if(s.props.shade)tags.push("木陰");if(s.props.water)tags.push("水辺");if(s.props.seating)tags.push("ベンチ");if(s.props.lowodor)tags.push("匂い少");const li=document.createElement("li");li.className="spot";li.innerHTML=`<div><strong>${name}</strong><br><small>${(s.tags.website||s.tags.operator||"")}</small></div><div>${tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div>`;list.appendChild(li);});}
async function runSearch(){let key=document.getElementById("region").value;let lat,lon;if(key==="current"){try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:8000}));lat=pos.coords.latitude;lon=pos.coords.longitude;}catch(e){alert("現在地が取得できませんでした。江坂を使用します。");key="esaka";lat=presets.esaka.lat;lon=presets.esaka.lon;document.getElementById("region").value="esaka";}}else{lat=presets[key].lat;lon=presets[key].lon;}const minutes=parseInt(document.getElementById("driveMin").value,10)||20;const profile=document.getElementById("speedProfile").value;const prio={indoor:parseInt(document.getElementById("prio-indoor").value,10)||1,shade:parseInt(document.getElementById("prio-shade").value,10)||2,water:parseInt(document.getElementById("prio-water").value,10)||3,seating:parseInt(document.getElementById("prio-seating").value,10)||2,lowodor:parseInt(document.getElementById("prio-lowodor").value,10)||1,};try{const results=await searchOverpass(lat,lon,minutes,profile,prio,10);renderSpotsList(results);}catch(e){const list=document.getElementById("spots");list.innerHTML="<li class='spot'>Overpassの取得に失敗しました。時間をおいて再試行してください。</li>";}}
window.addEventListener("load",()=>{runSearch();if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js");}});
document.getElementById("addToHome").addEventListener("click",()=>alert("Safariの共有 → 『ホーム画面に追加』でアプリ化できます。"));
document.getElementById("searchSpots").addEventListener("click",runSearch);