const presets = {
  esaka:{name:"大阪・江坂",lat:34.7565,lon:135.4968},
  kyoto:{name:"京都市",lat:35.038,lon:135.774},
  kobe:{name:"神戸市",lat:34.6913,lon:135.1830},
  omiya:{name:"さいたま市大宮区",lat:35.906,lon:139.624},
  fukushima:{name:"福島市",lat:37.7608,lon:140.4747},
};
function wbgtEstimate(t,rh){const e=(rh/100)*6.105*Math.exp((17.27*t)/(237.7+t));return 0.567*t+0.393*e+3.94;}
function heatIndexC(t,rh){const T=t*9/5+32,R=rh;const HI=-42.379+2.04901523*T+10.14333127*R-0.22475541*T*R-0.00683783*T*T-0.05481717*R*R+0.00122874*T*T*R+0.00085282*T*R*R-0.00000199*T*T*R*R;const H= T<80? T+(HI-T)*Math.max(0,(T-70)/10):HI;return (H-32)*5/9;}
function wbgtLevel(w){if(w<25)return{label:"注意",class:"safe",advice:"水分をこまめに。短時間の屋外はOK。"};if(w<28)return{label:"警戒",class:"caution",advice:"屋外は短時間に。日陰/屋内メインで。"};if(w<31)return{label:"厳重警戒",class:"high",advice:"午前のみ短時間、午後は屋内。"};return{label:"危険",class:"danger",advice:"外出は最小限に。冷房室内で。"};}
async function fetchWeatherAll(lat,lon){const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m&hourly=temperature_2m,precipitation_probability,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto`;return fetch(u).then(r=>r.json());}
function wmoIcon(c){if([0].includes(c))return"☀️";if([1,2,3].includes(c))return"⛅";if([45,48].includes(c))return"🌫";if([51,53,55,61,63,65,80,81,82].includes(c))return"🌧";if([71,73,75,85,86].includes(c))return"❄️";if([95,96,99].includes(c))return"⛈️";return"☁️";}
function renderHourly(h){const list=document.getElementById("hourly");list.innerHTML="";const now=new Date();for(let i=0;i<h.time.length;i++){const t=new Date(h.time[i]);if(t<now)continue;const hh=("0"+t.getHours()).slice(-2);const temp=h.temperature_2m[i];const pop=h.precipitation_probability?.[i];const icon=wmoIcon(h.weather_code?.[i]);const li=document.createElement("li");li.className="hour";li.innerHTML=`<span class="icon">${icon}</span> <strong>${hh}時</strong> ${temp.toFixed(0)}℃ ${pop!=null?`/ 降水${pop}%`:""}`;list.appendChild(li);if(list.children.length>=12)break;}}
function renderDaily(d){const list=document.getElementById("daily");list.innerHTML="";for(let i=0;i<d.time.length&&i<5;i++){const t=new Date(d.time[i]);const mm=t.getMonth()+1,dd=t.getDate();const icon=wmoIcon(d.weather_code?.[i]);const hi=d.temperature_2m_max?.[i];const lo=d.temperature_2m_min?.[i];const pop=d.precipitation_probability_max?.[i];const li=document.createElement("li");li.className="day";li.innerHTML=`<span class="icon">${icon}</span> <strong>${mm}/${dd}</strong> ${Math.round(lo)}–${Math.round(hi)}℃ ${pop!=null?`/ 降水${pop}%`:""}`;list.appendChild(li);}}
async function update(){let key=document.getElementById("region").value;let lat,lon;if(key==="current"){try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:8000}));lat=pos.coords.latitude;lon=pos.coords.longitude;}catch(e){alert("現在地が取得できませんでした。江坂を使用します。");key="esaka";lat=presets.esaka.lat;lon=presets.esaka.lon;document.getElementById("region").value="esaka";}}else{lat=presets[key].lat;lon=presets[key].lon;}
try{const data=await fetchWeatherAll(lat,lon);const temp=data?.current?.temperature_2m;const rh=data?.current?.relative_humidity_2m;const w=wbgtEstimate(temp,rh);const hi=heatIndexC(temp,rh);const lvl=wbgtLevel(w);document.getElementById("wbgtValue").textContent=w.toFixed(1);const b=document.getElementById("wbgtLevel");b.textContent=lvl.label;b.className="badge "+lvl.class;document.getElementById("temp").textContent=temp.toFixed(1);document.getElementById("rh").textContent=rh.toFixed(0);document.getElementById("heatIndex").textContent=hi.toFixed(1);document.getElementById("advice").textContent=lvl.advice+" 体調が悪くなったら無理せず休憩/帰宅を。";renderHourly(data.hourly||{});renderDaily(data.daily||{});}catch(e){document.getElementById("advice").textContent="天気データの取得に失敗しました。通信環境をご確認ください。";}}
window.addEventListener("load",()=>{update();if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js");}});
document.getElementById("refresh").addEventListener("click",update);
document.getElementById("addToHome").addEventListener("click",()=>alert("Safariの共有 → 『ホーム画面に追加』でアプリ化できます。"));
